version: '2'

services:
  srv:
    build: ../dv_trademe_go
    depends_on:
      - db
  db:
    build: ../dv_postgres
    ports:
      - "5432:5432"
    depends_on:
      - dbdata

  dbdata:
    build: ../dv_postgres
    volumes:
      - /var/lib/postgresql
